#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3    # All paddings use this value (icon, label, background)

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar position=bottom height=40 blur_radius=30 color=$BAR_COLOR
sketchybar --default icon.font="SF Pro:Semibold:15.0" \
  icon.color=$WHITE \
  label.font="SF Pro:Semibold:15.0" \
  label.color=$WHITE \
  background.color=$ITEM_BG_COLOR \
  background.corner_radius=5 \
  background.height=24 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=10 \
  icon.padding_left=10 \
  icon.padding_right=4
# default=(
#   padding_left=5
#   padding_right=5
#   icon.font="SF Pro:Semibold:15.0"
#   label.font="SF Pro:Semibold:15.0"
#   background.color=$ITEM_BG_COLOR
#   icon.color=$WHITE
#   label.color=$WHITE
#   icon.padding_left=4
#   icon.padding_right=4

source $ITEM_DIR/apple.sh
source $ITEM_DIR/aerospace.sh
# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/cpu.sh

sketchybar --update
